=== tomasbjerre/violations-lib/violations-lib/src/main/resources/jsonschemas/coverity-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "formatVersion": {
      "type": "integer"
    },
    "suppressedIssueCount": {
      "type": "integer"
    },
    "issues": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/issue"
      }
    },
    "desktopAnalysisSettings": {
      "type": "null"
    },
    "error": {
      "type": "null"
    },
    "warnings": {
      "type": "array",
      "items": {}
    }
  },
  "definitions": {
    "issue": {
      "type": "object",
      "properties": {
        "mergeKey": {
          "type": "string"
        },
        "occurrenceCountForMK": {
          "type": "integer"
        },
        "occurrenceNumberInMK": {
          "type": "integer"
        },
        "referenceOccurrenceCountForMK": {
          "type": "null"
        },
        "checkerName": {
          "type": "string"
        },
        "subcategory": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "subtype": {
          "type": "string"
        },
        "code-language": {
          "type": "string"
        },
        "extra": {
          "type": "string"
        },
        "domain": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "mainEventFilePathname": {
          "type": "string"
        },
        "strippedMainEventFilePathname": {
          "type": "string"
        },
        "mainEventLineNumber": {
          "type": "integer"
        },
        "properties": {
          "type": "object"
        },
        "functionDisplayName": {
          "type": "string"
        },
        "functionMangledName": {
          "type": "string"
        },
        "localStatus": {
          "type": "null"
        },
        "ordered": {
          "type": "boolean"
        },
        "stateOnServer": {
          "type": "null"
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/event"
          }
        },
        "checkerProperties": {
          "$ref": "#/definitions/checkerProperty"
        }
      }
    },
    "event": {
      "type": "object",
      "properties": {
        "covLStrEventDescription": {
          "type": "string"
        },
        "eventDescription": {
          "type": "string"
        },
        "eventNumber": {
          "type": "integer"
        },
        "eventTreePosition": {
          "type": "string"
        },
        "eventSet": {
          "type": "integer"
        },
        "eventTag": {
          "type": "string"
        },
        "filePathname": {
          "type": "string"
        },
        "strippedFilePathname": {
          "type": "string"
        },
        "lineNumber": {
          "type": "integer"
        },
        "main": {
          "type": "boolean"
        },
        "moreInformationId": {
          "type": "null"
        },
        "remediation": {
          "type": "boolean"
        },
        "events": {
          "type": "null"
        }
      }
    },
    "checkerProperty": {
      "type": "object",
      "properties": {
        "category": {
          "type": "string"
        },
        "categoryDescription": {
          "type": "string"
        },
        "cweCategory": {
          "type": "string"
        },
        "issueKinds": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/issueKind"
          }
        },
        "eventSetCaptions": {
          "type": "array",
          "items": {}
        },
        "impact": {
          "type": "string"
        },
        "impactDescription": {
          "type": "string"
        },
        "subcategoryLocalEffect": {
          "type": "string"
        },
        "subcategoryShortDescription": {
          "type": "string"
        },
        "subcategoryLongDescription": {
          "type": "string"
        }
      }
    },
    "issueKind": {
      "type": "string"
    }
  }
}

=== tomasbjerre/violations-lib/src/test/resources/coverity/example1.json
{
  "type": "Coverity issues",
  "formatVersion": 7,
  "suppressedIssueCount": 0,
  "issues": [
    {
      "mergeKey": "884ed7531feed32eb916d9038a3b9bd6",
      "occurrenceCountForMK": 1,
      "occurrenceNumberInMK": 1,
      "referenceOccurrenceCountForMK": null,
      "checkerName": "CONSTANT_EXPRESSION_RESULT",
      "subcategory": "bit_and_with_zero",
      "type": "constant_expression_result",
      "subtype": "bit_and_with_zero",
      "code-language": "c#",
      "extra": "status",
      "domain": "STATIC_CS",
      "language": "C#",
      "mainEventFilePathname": "C:\\Workspace\\workspace\\Build_jenkins_development\\somefile.cs",
      "strippedMainEventFilePathname": "\\workspace\\Build_jenkins_development\\Architecture\\somefile.cs",
      "mainEventLineNumber": 79,
      "properties": {},
      "functionDisplayName": "somename",
      "functionMangledName": "somename",
      "localStatus": null,
      "ordered": false,
      "events": [
        {
          "covLStrEventDescription": "{CovLStrv2{{t{{0} is always 0.}{{code{status & System.Printing.PrintJobStatus.None}}}}{t{ This occurs as a value.}}}}",
          "eventDescription": "\"status & System.Printing.PrintJobStatus.None\" is always 0. This occurs as a value.",
          "eventNumber": 1,
          "eventTreePosition": "1",
          "eventSet": 0,
          "eventTag": "bit_and_with_zero",
          "filePathname": "C:\\Workspace\\workspace\\Build_jenkins_development\\somefile.cs",
          "strippedFilePathname": "\\workspace\\Build_jenkins_development\\Architecture\\somefile.cs",
          "lineNumber": 79,
          "main": true,
          "moreInformationId": null,
          "remediation": false,
          "events": null
        }
      ],
      "stateOnServer": null,
      "checkerProperties": {
        "category": "Integer handling issues",
        "categoryDescription": "Integer handling issues",
        "cweCategory": "569",
        "issueKinds": ["QUALITY"],
        "eventSetCaptions": [],
        "impact": "Medium",
        "impactDescription": "Medium",
        "subcategoryLocalEffect": "The expression's value is always zero; construct may indicate an inadvertent logic error.",
        "subcategoryShortDescription": "Bitwise-and with zero",
        "subcategoryLongDescription": "Bitwise-and ('&amp;') operation applied to zero always produces zero"
      }
    }
  ],
  "desktopAnalysisSettings": null,
  "error": null,
  "warnings": []
}
